[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stepmesh"  # 他人 pip install 成功后的包名
version = "0.1.0"
description = "A CAD mesh processing package using Gmsh and NumPy"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "gmsh"
]

[tool.setuptools.packages.find]
where = ["."]